### ISSUE TITLE
Is there any plan to make an electron app for a bit more native experience 

### ISSUE THREAD

**Issue by satnam-sandhu** [zachomedia/apple-music-webplayer#98] opened 2019-09-03 14:30 UTC
I think many more people like me would love a native version of an apple music app.

**Comment by zachomedia** [comment] 2019-09-04 00:35
Thanks for the request, it's something on the radar but I haven't had the time to look into it. I'm going to close this as a duplicate of #6.

**Closed by zachomedia** 2019-09-04 00:35 UTC
