### ISSUE TITLE
Long tracks stop playing at 9:59

### ISSUE THREAD

**Issue by timbarclay** [zachomedia/apple-music-webplayer#40] opened 2018-08-29 14:59 UTC
Tracks longer than 10 minutes stop playing at 9:59 minutes. Nothing gets logged to the console.

**Comment by zachomedia** [comment] 2018-09-03 02:56
Thanks for the report. I was able to reproduce this. I'll look into the source of the error and either fix it or report it upstream.

**Comment by jaehess** [comment] 2018-10-24 00:51
@zachomedia Please ping me the number if you filed a Radar on this.

**Comment by zachomedia** [comment] 2018-10-24 03:16
@jaehess Unfortunately I've been quite busy recently and haven't had the chance to submit one yet. I was able to reproduce it however.

I'll try to submit one in the next few days.

**Comment by jaehess** [comment] 2018-10-24 03:38
No worries. I will take care of it. Do you happen to recall which browser you were using?

**Comment by zachomedia** [comment] 2018-10-24 03:39
I believe it was Chrome when I tested it (since I normally use that for dev purposes). If it wasn't Chrome, it was Safari.

**Comment by zachomedia** [comment] 2018-10-24 03:40
Just a note too, I had to let the song play from the start to 10 minutes. Sometimes scrubbing to near 10 minutes into the song wouldn't reproduce the issue.

**Comment by jaehess** [comment] 2018-10-24 18:49
Please label as Submitted to Apple. I am tracking this.

**Comment by zachomedia** [comment] 2018-11-07 03:40
I'm going to close this for now. If it's still an issue, we can re-open it.

**Closed** 2018-11-07 03:40 UTC
Labels: Submitted to Apple, bug
